services:
  - type: web
    name: mansfield-flash
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y python3-dev libxml2-dev libxslt1-dev && \
      pip install -r requirements.txt
    startCommand: gunicorn app:app
