name: Daily News Generator

# Run every day at 5 AM CT (10 AM UTC) and allow manual trigger
on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo without persisting default bot credentials
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4️⃣ Run your news generator script
      - name: Run news generator
        run: python generate_static_news.py
        
      # Push to Git
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add public/index.html
          git commit -m "Update static HTML [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/jehu22/mansfieldflash.git HEAD:main
